name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      # Uncomment the following step if you add tests to your project
      # - name: Run tests
      #   run: npm test

      - name: Configure git
        run: |
          git config --global user.email "info@champer.ru"
          git config --global user.name "Timur Iskakov"

      - name: Bump version and commit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git checkout -b temp-branch
          npm version patch -m "Bump version to %s"
          git add .
          git commit -m "Bump version to $(node -p -e "require('./package.json').version")"
          git push --set-upstream origin temp-branch
          git checkout main
          git merge temp-branch
          git push origin main
          git branch -d temp-branch

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
