name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Bump version and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLICATION_TOKEN }}
        run: |
          git config --global user.email "info@champer.ru"
          git config --global user.name "Timur Iskakov"
          npm version patch -m "Bump version to %s"
          git push origin main
          npm publish --access public
